---
abstract: '[DEFUNCT] Attribute trait to cascade clearer actions'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  ExtUtils::MakeMaker: 6.42
  FindBin: 0
  Test::More: 0
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.91'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Traits-Attribute-CascadeClear
no_index:
  directory:
    - inc
    - t
    - xt
requires:
  Moose: 0.64
  Moose::Role: 0.64
resources:
  license: http://opensource.org/licenses/lgpl-license.php
version: 0.04
