---
abstract: 'Attribute trait to cascade clearer actions'
author:
  - 'Chris Weyl <cweyl@alumni.drew.edu>'
build_requires:
  FindBin: 0
  Test::More: 0
distribution_type: module
generated_by: 'Module::Install version 0.77'
license: lgpl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: MooseX-Traits-Attribute-CascadeClear
no_index:
  directory:
    - inc
    - t
requires:
  Moose: 0
  Moose::Role: 0
version: 0.02
